### ISSUE TITLE
Create new config

### ISSUE THREAD

**Issue by clburlison** [kylecrawshaw/ImagrAdmin#4]
Currently when ImagrAdmin launches you are forced to select an existing config file for modification. We should have the option to create a new config file from scratch. 

That might have implementations for the save button. Not actually sure on that part.

**Comment by kylecrawshaw** [comment]
This is something I plan to do. The user will be presented with that option before anything else happens. I'll also add in the option to create a "new" config file from the file menu and the user will be prompted to save and close the current one.

**Comment by kylecrawshaw** [comment]
This is close to done, but it requires some decent modifications to the code base. Refactoring in the process and adding comments. Should this resolved next week. After this and getting the menus wired up I'll probably release the first beta. Thoughts?

**Comment by clburlison** [comment]
For sure. Would definitely open up a first beta release after this issue is resolved. All of the core features that I've tested are working as intended.

**Comment by kylecrawshaw** [comment]
This issue should now be resolved as of https://github.com/kylecrawshaw/ImagrAdmin/pull/10. Not quite ready for a beta yet though. I would like to address https://github.com/kylecrawshaw/ImagrAdmin/issues/6 and https://github.com/kylecrawshaw/ImagrAdmin/issues/5 before that.

**Comment by kylecrawshaw** [comment]
Fixed in https://github.com/kylecrawshaw/ImagrAdmin/pull/10. I'll probably change the welcome screen at some point. It is pretty bland right now, but it works.
