### ISSUE TITLE
Application state on red x click

### ISSUE THREAD

**Issue by clburlison** [kylecrawshaw/ImagrAdmin#5]
Currently ImagrAdmin is left running but in a useless state when the Red X  is clicked to close the app. 

The really simple solution is https://github.com/kylecrawshaw/ImagrAdmin/compare/master...clburlison:closeOnRedX. 

A better option would be to handle this in the `MainViewController` (I think). Then we should be able to prompt the end user if they want to save when they have modifications. I don't believe you can/should handle that type of task in the `AppDelegate` which is why I don't recommend the above.

**Comment by kylecrawshaw** [comment]
@clburlison This makes sense, but the AppDelegate could also send an NSNotification to MainViewController when this occurs. Would just need to create a notification when that method gets called in AppDelegate, a receiver and a function to call when the receiver gets a notification.

**Comment by kylecrawshaw** [comment]
Nevermind. I didn't look closely enough to realize it's a boolean. I'll see what other ways I can go about this.

**Comment by kylecrawshaw** [comment]
@clburlison So after some thought I think I'm going to disable the close button on the main window. If it remains enabled I need to either quit the application when closed or have a mechanism to make it visible again. It seems like if someone had one or more "Edit Workflow" windows visible, but the main window was gone it could be quite confusing. I will keep the minimize and full screen buttons though. Open to a discussion if you think it makes sense to keep the close button.

**Comment by clburlison** [comment]
I completely agree with that solution. Just make it so ImagrAdmin can't get into a bad state and all is 👍

**Comment by kylecrawshaw** [comment]
Resolved and merged in https://github.com/kylecrawshaw/ImagrAdmin/pull/11
