### ISSUE TITLE
Validation task terminated

### ISSUE THREAD

**Issue by clburlison** [kylecrawshaw/ImagrAdmin#7]
Clicking the "Skip" button on the validation window causes a hard crash. I'm not super sure if the skip button even needs to exist. The validation process is pretty fast even when doing lots of http header checks. Might be better to force users to click the "Ok" button. 

``` bash
build/Release/ImagrAdmin.app/Contents/MacOS/ImagrAdmin
2016-07-26 09:13:09.678 ImagrAdmin[10885:8849353] User selected path /Users/clburlison/Desktop/min_case_skip.plist
2016-07-26 09:13:09.679 ImagrAdmin[10885:8849353] Need to validate /Users/clburlison/Desktop/min_case_skip.plist
2016-07-26 09:13:09.684 ImagrAdmin[10885:8849353] Initialized ImagrConfigManager.sharedManager with /Users/clburlison/Desktop/min_case_skip.plist
2016-07-26 09:13:09.684 ImagrAdmin[10885:8849353] Updating config view
2016-07-26 09:13:10.359 ImagrAdmin[10885:8849353] Validation task terminated
[1]    10885 illegal hardware instruction  build/Release/ImagrAdmin.app/Contents/MacOS/ImagrAdmin
```

[min_case_skip.txt](https://github.com/kylecrawshaw/ImagrAdmin/files/383994/min_case_skip.txt)

**Comment by kylecrawshaw** [comment]
@clburlison The skip button was added because you may not always be in reach out certain packages and scripts if they are behind a firewall or require VPN access. I think this could possibly be handled a bit differently, but that may require some changes to validateplist

**Comment by kylecrawshaw** [comment]
I'll try to figure out why the hard crash is occuring

**Comment by clburlison** [comment]
Sure I understand the VPN part. However, the validation task starts once you select the config file. By the time you see the "Skip" button the validation task has already output it's info to your Log window since we're only checking the head of the http request. The only time I can see the skip button being useful is if you have really bad network connection. _My two cents_.

This might be a good enhancement request for Imagr and the validation script to output color. That way ERROR, WARNING, SUCESS stand out more.

**Comment by kylecrawshaw** [comment]
@clburlison it shouldn't be too difficult to parse for those words and change the line color. An attributedStringValue can then be used in the NSTextView. I think outputting the color in validateplist would only help here if the returned text from NSTask contains the the same color values as Swift would expect, which may very well be the case.

**Comment by kylecrawshaw** [comment]
@clburlison I changed it so that errors,warning and success messages are the appropriate colors. Also, I'll make the skip button disappear in the validate window when the task is finished. That'll stop the error from happening.

**Comment by kylecrawshaw** [comment]
This is now resolved in PR https://github.com/kylecrawshaw/ImagrAdmin/pull/9
